name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-terraform:
    name: "Run terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: "${{ secrets.AWS_ROLE }}/tf-role"
          aws-region: us-east-1

      - name: Setup terraform
        uses: "hashicorp/setup-terraform@v3"
        with:
          terraform_version: 1.14.3

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
